[tool.poetry]
name = "openconnect-sso"
version = "0.8.0"
description = "Wrapper script for OpenConnect supporting Azure AD (SAMLv2) authentication to Cisco SSL-VPNs"
license = "GPL-3.0-only"
authors = ["László Vaskó <laszlo.vasko@outlook.com>"]
readme = "README.md"
homepage = "https://github.com/vlaci/openconnect-sso"
repository = "https://github.com/vlaci/openconnect-sso"

classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: X11 Applications :: Qt",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
    "Topic :: System :: Networking",
]

[tool.poetry.scripts]
openconnect-sso = "openconnect_sso.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
colorama = "^0.4"
importlib-metadata = { version = "^3.10.0", python = "<3.8" }
lxml = "^4.3"
keyring = ">=21.1, <24.0.0"
prompt-toolkit = "^3.0.3"
pyxdg = ">=0.26, <0.28"
requests = "^2.22"
structlog = ">=20.1"
toml = "^0.10"
setuptools = ">40.0"

PySocks = "^1.7.1"
selenium = "^4.1.0"
webdriver-manager = "^3.5.2"

[tool.poetry.extras]
full = [ "PyQt5", "PyQtWebEngine" ]

[tool.poetry.dev-dependencies]
coverage_enable_subprocess = "^1.0"
black = "^22.3.0"
mypy = "^0.942"
pytest = "^7.1.2"
pytest-asyncio = "^0.17.0"
pytest-cov = "^3.0.0"
pytest-httpserver = "^1.0"
# Fix installation of zipp dependency of importlib-metadata
setuptools-scm = { version ="^3.4", extras = ["toml"] }
types-requests = "^2.27.20"
types-selenium = "^3.141.9"
types-toml = "^0.10.5"

[tool.black]
target-version = ['py37']

[tool.isort]
py_version = 37
profile = "black"

[tool.mypy]
strict = true
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1"]
build-backend = "poetry.core.masonry.api"
